sudo: required
language: python
python:
- '3.8'
install:
- pip install molecule docker yamllint ansible-lint
script:
- molecule --version
- ansible --version
- yamllint main.yml
- ansible-lint main.yml 
- cd roles/centos_docker
- molecule test 
