---
- name: Create VM
  hosts: localhost
  connection: local
  tasks:
    - include_tasks: azure_create_vm.yml
      loop: "{{ users }}"


- name: Install docker
  hosts: vms
  roles:
    - centos_docker
