---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint . -d relaxed
  ansible-lint
platforms:
  - name: centos
    image: centos/systemd:latest
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
