---
- name: Enable EPEL Repository on CentOS 7
  yum:
    name: epel-release

- name: Install required packages
  yum:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - python-pip
      - python-setuptools
      - yum-utils
      - lvm2

- name: Remove docker if installed from CentOS repo
  yum:
    name: "{{ docker_versions }}"
    state: removed
  vars:
    docker_versions:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine

- name: "Check if Docker is installed"
  package_facts:
    manager: "auto"

- name: Check if docker-ce.repo exists
  stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: stat_result

- name: Add Docker repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: not stat_result.stat.exists

- name: Install Docker ce
  yum:
    name: docker-ce
    update_cache: yes

- name: Add user to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
  become: yes

- name: Installing Docker SDK for python
  pip:
    name:
      - docker
    state: present

- name: Start and enable docker service
  service:
    name: "docker"
    state: started
    enabled: yes


